# FROM ubuntu:xenial-20171114
FROM ubuntu:16.04

# Add the user "user" non interactively thanks to https://askubuntu.com/a/94067/29219 and add it to the sudoers without password asked thanks to https://askubuntu.com/a/192062/29219
ARG USER_UID
ARG USER_GID
ARG http_proxy
ARG https_proxy
ARG HTTP_PROXY
ARG HTTPS_PROXY
RUN addgroup --gid $USER_GID user && \
    adduser --uid $USER_UID --gid $USER_GID --disabled-password --gecos "" user && \
    apt-get update && apt-get install -y sudo && echo "user ALL=(ALL) NOPASSWD:ALL" >>/etc/sudoers

ADD setup/dev-env-on-ubuntu-16.04.sh /usr/local/bin/setup.sh
USER user
ADD setup/proxy-on-ubuntu.sh /opt/debattons/setup/proxy-on-ubuntu.sh
RUN setup.sh --no-debattons-git-copy

WORKDIR /opt/debattons

ADD scripts/build-and-run.dev.sh /usr/local/bin/build-and-run.dev.sh

CMD build-and-run.dev.sh --orientdb-host orientdb
