# FROM ubuntu:xenial-20171114
FROM ubuntu:16.04

# Add the user "user" non interactively thanks to https://askubuntu.com/a/94067/29219 and add it to the sudoers without password asked thanks to https://askubuntu.com/a/192062/29219
ARG USER_UID
ARG USER_GID
RUN addgroup --gid $USER_GID user && \
    adduser --uid $USER_UID --gid $USER_GID --disabled-password --gecos "" user && \
    apt-get update && apt-get install -y sudo && echo "user ALL=(ALL) NOPASSWD:ALL" >>/etc/sudoers

ADD setup/dev-env-on-ubuntu-16.04.sh /usr/local/bin/setup.sh
USER user
RUN setup.sh --no-run-env

# Install OrientDB tools (inspired by the Docker script https://github.com/orientechnologies/orientdb-docker/blob/222b64299884eeb4b324e2822873f69e8a7c006e/3.0/x86_64/alpine/Dockerfile)
## Using 2.2.30 instead of 3.0.0m2 because of a bug when creating a user from the console https://stackoverflow.com/q/47446065/535203 and https://github.com/orientechnologies/orientdb/issues/7898
ENV ORIENTDB_VERSION 2.2.30
ENV ORIENTDB_DOWNLOAD_URL ${ORIENTDB_DOWNLOAD_SERVER:-http://central.maven.org/maven2/com/orientechnologies}/orientdb-community/$ORIENTDB_VERSION/orientdb-community-$ORIENTDB_VERSION.tar.gz
USER root
RUN apt-get install -y wget && \
  mkdir /opt/orientdb && \
  wget  $ORIENTDB_DOWNLOAD_URL \
  && tar -xvzf orientdb-community-$ORIENTDB_VERSION.tar.gz -C /opt/orientdb --strip-components=1 \
  && rm orientdb-community-$ORIENTDB_VERSION.tar.gz

# Install cmd.sh dependencies
RUN apt-get install -y netcat

USER user

WORKDIR /opt/debattons

ADD docker/debattons-docker-cmd.dev.sh /usr/local/bin/cmd.sh

CMD cmd.sh
